Re-enable long chain of jobs covering all OS platforms

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -4,134 +4,135 @@ name: PR
 on: pull_request
 
 jobs:
-#   build-linux:
-#     runs-on: ubuntu-latest
-#     continue-on-error: true
-#     env:
-#       # https://github.com/actions/setup-dotnet/blob/main/README.md#environment-variables
-#       DOTNET_INSTALL_DIR: "/usr/share/dotnet" # don't override by /usr/lib/dotnet 
-#       NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
-#     steps:
-#     - name: Checkout
-#       uses: actions/checkout@v5
-#     - name: SH-scripts executable
-#       run: |
-#         chmod +x .github/steps/*.sh
-#         ls -l .github/steps/*.sh
-#     - name: Check .NET 10
-#       id: check-dotnet10
-#       run: ./.github/steps/check-dotnet.sh 10
-#     - name: Setup .NET 10
-#       # if: env.DOTNET10_installed == 'false'
-#       uses: actions/setup-dotnet@v5
-#       with:
-#         dotnet-version: 10.x
-#         cache: true
-#         cache-dependency-path: |
-#           samples/**/packages.lock.json
-#           src/**/packages.lock.json
-#           test/**/packages.lock.json
-#     - name: .NET Info
-#       run: dotnet --info
-#     - name: Add DNS-records
-#       run: ./.github/steps/ubuntu.add-dns-records.sh  
-#     - name: Install certificate
-#       run: ./.github/steps/ubuntu.install-certificate.sh
-#     - name: Restore
-#       run: dotnet restore --locked-mode ./Ocelot.slnx
-#     - name: Build
-#       run: dotnet build --no-restore ./Ocelot.slnx --framework net10.0
-#     - name: Unit Tests
-#       run: dotnet test --no-restore --no-build --verbosity normal --framework net10.0 --settings coverlet.runsettings ./test/Ocelot.UnitTests/Ocelot.UnitTests.csproj
-#     - name: Acceptance Tests
-#       run: dotnet test --no-restore --no-build --verbosity normal --framework net10.0 --settings coverlet.runsettings ./test/Ocelot.AcceptanceTests/Ocelot.AcceptanceTests.csproj
+  build-linux:
+    runs-on: ubuntu-latest
+    continue-on-error: true
+    env:
+      # https://github.com/actions/setup-dotnet/blob/main/README.md#environment-variables
+      DOTNET_INSTALL_DIR: "/usr/share/dotnet" # don't override by /usr/lib/dotnet 
+      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v6
+    - name: SH-scripts executable
+      run: |
+        chmod +x .github/steps/*.sh
+        ls -l .github/steps/*.sh
+    - name: Check .NET 10
+      id: check-dotnet10
+      run: ./.github/steps/check-dotnet.sh 10
+    - name: Setup .NET 10
+      # if: env.DOTNET10_installed == 'false'
+      uses: actions/setup-dotnet@v5
+      with:
+        dotnet-version: 10.x
+        cache: true
+        cache-dependency-path: |
+          samples/**/packages.lock.json
+          src/**/packages.lock.json
+          test/**/packages.lock.json
+    - name: .NET Info
+      run: dotnet --info
+    - name: Add DNS-records
+      run: ./.github/steps/ubuntu.add-dns-records.sh  
+    - name: Install certificate
+      run: ./.github/steps/ubuntu.install-certificate.sh
+    - name: Restore
+      run: dotnet restore --locked-mode ./Ocelot.slnx
+    - name: Build
+      run: dotnet build --no-restore ./Ocelot.slnx --framework net10.0
+    - name: Unit Tests
+      run: dotnet test --no-restore --no-build --verbosity normal --framework net10.0 --settings coverlet.runsettings ./test/Ocelot.UnitTests/Ocelot.UnitTests.csproj
+    - name: Acceptance Tests
+      run: dotnet test --no-restore --no-build --verbosity normal --framework net10.0 --settings coverlet.runsettings ./test/Ocelot.AcceptanceTests/Ocelot.AcceptanceTests.csproj
 
-#   build-macos:
-#     runs-on: macos-latest
-#     continue-on-error: true
-#     env:
-#       NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
-#     steps:
-#       - name: Checkout
-#         uses: actions/checkout@v5
-#       - name: SH-scripts executable
-#         run: |
-#           chmod +x .github/steps/*.sh
-#           ls -l .github/steps/*.sh
-#       - name: Setup .NET 10
-#         uses: actions/setup-dotnet@v5
-#         with:
-#           dotnet-version: 10.x
-#           cache: true
-#           cache-dependency-path: |
-#             samples/**/packages.lock.json
-#             src/**/packages.lock.json
-#             test/**/packages.lock.json
-#       - name: .NET Info
-#         run: dotnet --info
-#       - name: Add DNS-records
-#         run: ./.github/steps/macos.add-dns-records.sh  
-#       - name: Install certificate
-#         run: ./.github/steps/macos.install-certificate.sh
-#       - name: Restore
-#         run: dotnet restore --locked-mode ./Ocelot.slnx
-#       - name: Build
-#         run: dotnet build --no-restore ./Ocelot.slnx --framework net10.0
-#       - name: Unit Tests
-#         run: dotnet test --no-restore --no-build --verbosity minimal --framework net10.0 --settings coverlet.runsettings ./test/Ocelot.UnitTests/Ocelot.UnitTests.csproj
-#       - name: Acceptance Tests
-#         run: dotnet test --no-restore --no-build --verbosity minimal --framework net10.0 --settings coverlet.runsettings ./test/Ocelot.AcceptanceTests/Ocelot.AcceptanceTests.csproj
+  build-macos:
+    runs-on: macos-latest
+    continue-on-error: true
+    env:
+      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v6
+      - name: SH-scripts executable
+        run: |
+          chmod +x .github/steps/*.sh
+          ls -l .github/steps/*.sh
+      - name: Setup .NET 10
+        uses: actions/setup-dotnet@v5
+        with:
+          dotnet-version: 10.x
+          cache: true
+          cache-dependency-path: |
+            samples/**/packages.lock.json
+            src/**/packages.lock.json
+            test/**/packages.lock.json
+      - name: .NET Info
+        run: dotnet --info
+      - name: Add DNS-records
+        run: ./.github/steps/macos.add-dns-records.sh  
+      - name: Install certificate
+        run: ./.github/steps/macos.install-certificate.sh
+      - name: Restore
+        run: dotnet restore --locked-mode ./Ocelot.slnx
+      - name: Build
+        run: dotnet build --no-restore ./Ocelot.slnx --framework net10.0
+      - name: Unit Tests
+        run: dotnet test --no-restore --no-build --verbosity minimal --framework net10.0 --settings coverlet.runsettings ./test/Ocelot.UnitTests/Ocelot.UnitTests.csproj
+      - name: Acceptance Tests
+        run: dotnet test --no-restore --no-build --verbosity minimal --framework net10.0 --settings coverlet.runsettings ./test/Ocelot.AcceptanceTests/Ocelot.AcceptanceTests.csproj
 
-#   build-windows:
-#     runs-on: windows-latest
-#     continue-on-error: true
-#     env:
-#       NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
-#     steps:
-#       - name: Checkout
-#         uses: actions/checkout@v5
-#       - name: Setup .NET 10
-#         uses: actions/setup-dotnet@v5
-#         with:
-#           dotnet-version: 10.x
-#           cache: true
-#           cache-dependency-path: |
-#             samples/**/packages.lock.json
-#             src/**/packages.lock.json
-#             test/**/packages.lock.json
-#       - name: .NET Info
-#         run: dotnet --info
-#       - name: Add DNS-records
-#         run: ./.github/steps/windows.add-dns-records.ps1  
-#       - name: Install certificate
-#         run: ./.github/steps/windows.install-certificate.ps1
-#       - name: Restore
-#         run: dotnet restore --locked-mode ./Ocelot.slnx
-#       - name: Build
-#         run: dotnet build --no-restore ./Ocelot.slnx --framework net10.0
-#       - name: Unit Tests
-#         run: dotnet test --no-restore --no-build --verbosity minimal --framework net10.0 --settings coverlet.runsettings ./test/Ocelot.UnitTests/Ocelot.UnitTests.csproj
-#       - name: Acceptance Tests
-#         run: dotnet test --no-restore --no-build --verbosity minimal --framework net10.0 --settings coverlet.runsettings ./test/Ocelot.AcceptanceTests/Ocelot.AcceptanceTests.csproj
+  build-windows:
+    runs-on: windows-latest
+    continue-on-error: true
+    env:
+      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v6
+      - name: Setup .NET 10
+        uses: actions/setup-dotnet@v5
+        with:
+          dotnet-version: 10.x
+          cache: true
+          cache-dependency-path: |
+            samples/**/packages.lock.json
+            src/**/packages.lock.json
+            test/**/packages.lock.json
+      - name: .NET Info
+        run: dotnet --info
+      - name: Add DNS-records
+        run: ./.github/steps/windows.add-dns-records.ps1  
+      - name: Install certificate
+        run: ./.github/steps/windows.install-certificate.ps1
+      - name: Restore
+        run: dotnet restore --locked-mode ./Ocelot.slnx
+      - name: Build
+        run: dotnet build --no-restore ./Ocelot.slnx --framework net10.0
+      - name: Unit Tests
+        run: dotnet test --no-restore --no-build --verbosity minimal --framework net10.0 --settings coverlet.runsettings ./test/Ocelot.UnitTests/Ocelot.UnitTests.csproj
+      - name: Acceptance Tests
+        run: dotnet test --no-restore --no-build --verbosity minimal --framework net10.0 --settings coverlet.runsettings ./test/Ocelot.AcceptanceTests/Ocelot.AcceptanceTests.csproj
 
-#   build-success:
-#     needs: [build-linux, build-macos, build-windows]
-#     runs-on: ubuntu-latest
-#     if: ${{ always() }} # run even Linux / MacOS / Windows build fails
-#     steps:
-#       - name: Decide success
-#         run: |
-#           linux_result="${{ needs.build-linux.result }}"
-#           macos_result="${{ needs.build-macos.result }}"
-#           windows_result="${{ needs.build-windows.result }}"
-#           if [[ $linux_result == "success" || $macos_result == "success" || $windows_result == "success" ]]; then
-#             echo "At least one succeeded"
-#           else
-#             echo "All failed"
-#             exit 1
-#           fi
+  build-success:
+    needs: [build-linux, build-macos, build-windows]
+    runs-on: ubuntu-latest
+    if: ${{ always() }} # run even Linux / MacOS / Windows build fails
+    steps:
+      - name: Decide success
+        run: |
+          linux_result="${{ needs.build-linux.result }}"
+          macos_result="${{ needs.build-macos.result }}"
+          windows_result="${{ needs.build-windows.result }}"
+          if [[ $linux_result == "success" || $macos_result == "success" || $windows_result == "success" ]]; then
+            echo "At least one succeeded"
+          else
+            echo "All failed"
+            exit 1
+          fi
 
   build-cake:
+    needs: [build-linux, build-macos, build-windows]
     runs-on: ubuntu-latest
     # environment: Pull-Request
     env:
@@ -139,7 +140,7 @@ jobs:
       NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
     steps:
       - name: Checkout
-        uses: actions/checkout@v5
+        uses: actions/checkout@v6
         with:
           fetch-depth: 0
       - name: SH-scripts executable
@@ -181,11 +182,11 @@ jobs:
         continue-on-error: true
       - name: Codecov
         if: env.COVERALLS_coverage_file_exists == 'true'
-        uses: codecov/codecov-action@v5
+        uses: codecov/codecov-action@v6
         with:
           token: ${{ secrets.CODECOV_TOKEN }}
           slug: ThreeMammals/Ocelot
           fail_ci_if_error: true
           files: ${{ env.COVERALLS_coverage_file }}
-          flags: unittests
+          flags: unit
         continue-on-error: true
