Disable TRX file creation due to expected exit code 0

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -239,21 +239,21 @@ jobs:
       - name: Unit Tests
         run: |
           dotnet test --no-restore --no-build --verbosity normal --framework net10.0 --project ./test/Ocelot.UnitTests/Ocelot.UnitTests.csproj \
-            --coverlet --coverlet-include "[Ocelot*]*" --coverlet-exclude "[Ocelot.Testing]*" \
-            --report-xunit-trx --report-xunit-trx-filename=unit-tests.trx | tee test_output.txt
-          if grep -q "failed: 0" test_output.txt; then
-            echo "✓ Test run successful"
-            exit 0
-          else
-            echo "✗ Test run failed: No 'failed: 0' found"
-            exit 1
-          fi
-      - name: Upload Test Results
-        if: always()
-        uses: actions/upload-artifact@v4
-        with:
-          name: unit-tests-trx
-          path: "test/Ocelot.UnitTests/bin/Debug/**/unit-tests.trx"
+            --coverlet --coverlet-include "[Ocelot*]*" --coverlet-exclude "[Ocelot.Testing]*"
+          # --report-xunit-trx --report-xunit-trx-filename=unit-tests.trx | tee test_output.txt
+          # if grep -q "failed: 0" test_output.txt; then
+          #   echo "✓ Test run successful"
+          #   exit 0
+          # else
+          #   echo "✗ Test run failed: No 'failed: 0' found"
+          #   exit 1
+          # fi
+      # - name: Upload Test Results
+      #   if: always()
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: unit-tests-trx
+      #     path: "test/Ocelot.UnitTests/bin/Debug/**/unit-tests.trx"
       - name: Acceptance Tests
         run: dotnet test --no-restore --no-build --verbosity minimal --framework net10.0 --project ./test/Ocelot.AcceptanceTests/Ocelot.AcceptanceTests.csproj
       - name: Coverage files
