Matrix build with max-parallel:3

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -4,15 +4,156 @@ name: PR
 on: pull_request
 
 jobs:
-  build-linux:
+  # build-linux:
+  #   strategy:
+  #     matrix:
+  #       dotnet-version: [ 8, 9, 10 ]
+  #   runs-on: ubuntu-latest
+  #   # continue-on-error: true
+  #   env:
+  #     # https://github.com/actions/setup-dotnet/blob/main/README.md#environment-variables
+  #     DOTNET_INSTALL_DIR: "/usr/share/dotnet" # don't override by /usr/lib/dotnet 
+  #     NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
+  #   steps:
+  #   - name: Checkout
+  #     uses: actions/checkout@v6
+  #   - name: SH-scripts executable
+  #     run: |
+  #       chmod +x .github/steps/*.sh
+  #       ls -l .github/steps/*.sh
+  #   - name: Check .NET ${{ matrix.dotnet-version }}
+  #     id: checkdotnet
+  #     run: ./.github/steps/check-dotnet.sh ${{ matrix.dotnet-version }}
+  #   - name: Setup .NET ${{ matrix.dotnet-version }}
+  #     # if: steps.checkdotnet.outputs.checkdotnet_installed == 'false'
+  #     uses: actions/setup-dotnet@v5
+  #     with:
+  #       dotnet-version: ${{ matrix.dotnet-version }}.x
+  #       cache: true
+  #       cache-dependency-path: |
+  #         samples/**/packages.lock.json
+  #         src/**/packages.lock.json
+  #         test/**/packages.lock.json
+  #   - name: .NET Info
+  #     run: dotnet --info
+  #   - name: Add DNS-records
+  #     run: ./.github/steps/ubuntu.add-dns-records.sh  
+  #   - name: Install certificate
+  #     run: ./.github/steps/ubuntu.install-certificate.sh
+  #   - name: Restore
+  #     run: dotnet restore --locked-mode ./Ocelot.slnx
+  #   - name: Build
+  #     run: dotnet build --no-restore ./Ocelot.slnx --framework net${{ matrix.dotnet-version }}.0
+  #   - name: Unit Tests
+  #     run: dotnet test --no-restore --no-build --verbosity minimal --framework net${{ matrix.dotnet-version }}.0 --settings coverlet.runsettings ./test/Ocelot.UnitTests/Ocelot.UnitTests.csproj
+  #   - name: Acceptance Tests
+  #     run: dotnet test --no-restore --no-build --verbosity minimal --framework net${{ matrix.dotnet-version }}.0 --settings coverlet.runsettings ./test/Ocelot.AcceptanceTests/Ocelot.AcceptanceTests.csproj
+
+  # build-macos:
+  #   needs: build-linux
+  #   strategy:
+  #     matrix:
+  #       dotnet-version: [ 8, 9, 10 ]
+  #   runs-on: macos-latest
+  #   # continue-on-error: true
+  #   env:
+  #     NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v6
+  #     - name: SH-scripts executable
+  #       run: |
+  #         chmod +x .github/steps/*.sh
+  #         ls -l .github/steps/*.sh
+  #     - name: Setup .NET ${{ matrix.dotnet-version }}
+  #       uses: actions/setup-dotnet@v5
+  #       with:
+  #         dotnet-version: ${{ matrix.dotnet-version }}.x
+  #         cache: true
+  #         cache-dependency-path: |
+  #           samples/**/packages.lock.json
+  #           src/**/packages.lock.json
+  #           test/**/packages.lock.json
+  #     - name: .NET Info
+  #       run: dotnet --info
+  #     - name: Add DNS-records
+  #       run: ./.github/steps/macos.add-dns-records.sh  
+  #     - name: Install certificate
+  #       run: ./.github/steps/macos.install-certificate.sh
+  #     - name: Restore
+  #       run: dotnet restore --locked-mode ./Ocelot.slnx
+  #     - name: Build
+  #       run: dotnet build --no-restore ./Ocelot.slnx --framework net${{ matrix.dotnet-version }}.0
+  #     - name: Unit Tests
+  #       run: dotnet test --no-restore --no-build --verbosity minimal --framework net${{ matrix.dotnet-version }}.0 --settings coverlet.runsettings ./test/Ocelot.UnitTests/Ocelot.UnitTests.csproj
+  #     - name: Acceptance Tests
+  #       run: dotnet test --no-restore --no-build --verbosity minimal --framework net${{ matrix.dotnet-version }}.0 --settings coverlet.runsettings ./test/Ocelot.AcceptanceTests/Ocelot.AcceptanceTests.csproj
+
+  # build-windows:
+  #   needs: build-macos
+  #   strategy:
+  #     matrix:
+  #       dotnet-version: [ 8, 9, 10 ]
+  #   runs-on: windows-latest
+  #   # continue-on-error: true
+  #   env:
+  #     NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v6
+  #     - name: Setup .NET ${{ matrix.dotnet-version }}
+  #       uses: actions/setup-dotnet@v5
+  #       with:
+  #         dotnet-version: ${{ matrix.dotnet-version }}.x
+  #         cache: true
+  #         cache-dependency-path: |
+  #           samples/**/packages.lock.json
+  #           src/**/packages.lock.json
+  #           test/**/packages.lock.json
+  #     - name: .NET Info
+  #       run: dotnet --info
+  #     - name: Add DNS-records
+  #       run: ./.github/steps/windows.add-dns-records.ps1  
+  #     - name: Install certificate
+  #       run: ./.github/steps/windows.install-certificate.ps1
+  #     - name: Restore
+  #       run: dotnet restore --locked-mode ./Ocelot.slnx
+  #     - name: Build
+  #       run: dotnet build --no-restore ./Ocelot.slnx --framework net${{ matrix.dotnet-version }}.0
+  #     - name: Unit Tests
+  #       run: dotnet test --no-restore --no-build --verbosity minimal --framework net${{ matrix.dotnet-version }}.0 --settings coverlet.runsettings ./test/Ocelot.UnitTests/Ocelot.UnitTests.csproj
+  #     - name: Acceptance Tests
+  #       run: dotnet test --no-restore --no-build --verbosity minimal --framework net${{ matrix.dotnet-version }}.0 --settings coverlet.runsettings ./test/Ocelot.AcceptanceTests/Ocelot.AcceptanceTests.csproj
+
+  # build-success:
+  #   needs: [build-linux, build-macos, build-windows]
+  #   runs-on: ubuntu-latest
+  #   if: ${{ always() }} # run even Linux / MacOS / Windows build fails
+  #   steps:
+  #     - name: Decide success
+  #       run: |
+  #         linux_result="${{ needs.build-linux.result }}"
+  #         macos_result="${{ needs.build-macos.result }}"
+  #         windows_result="${{ needs.build-windows.result }}"
+  #         if [[ $linux_result == "success" || $macos_result == "success" || $windows_result == "success" ]]; then
+  #           echo "At least one succeeded"
+  #         else
+  #           echo "All failed"
+  #           exit 1
+  #         fi
+
+  # Matrix build job having 2 dimensions (os, ver)
+  build:
     strategy:
+      max-parallel: 3
       matrix:
-        dotnet-version: [ 8, 9, 10 ]
-    runs-on: ubuntu-latest
-    # continue-on-error: true
+        os: [ubuntu, macos, windows]
+        version: [8, 9, 10]
+    runs-on: ${{ matrix.os }}-latest
+    defaults:
+      run:
+        shell: bash
     env:
-      # https://github.com/actions/setup-dotnet/blob/main/README.md#environment-variables
-      DOTNET_INSTALL_DIR: "/usr/share/dotnet" # don't override by /usr/lib/dotnet 
       NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
     steps:
     - name: Checkout
@@ -21,14 +162,14 @@ jobs:
       run: |
         chmod +x .github/steps/*.sh
         ls -l .github/steps/*.sh
-    - name: Check .NET ${{ matrix.dotnet-version }}
-      id: check-dotnet
-      run: ./.github/steps/check-dotnet.sh ${{ matrix.dotnet-version }}
-    - name: Setup .NET ${{ matrix.dotnet-version }}
-      # if: env.DOTNET${{ matrix.dotnet-version }}_installed == 'false'
+    - name: Check .NET ${{ matrix.version }}
+      id: checkdotnet
+      run: ./.github/steps/check-dotnet.sh ${{ matrix.version }}
+    - name: Setup .NET ${{ matrix.version }}
+      # if: steps.checkdotnet.outputs.checkdotnet_installed == 'false'
       uses: actions/setup-dotnet@v5
       with:
-        dotnet-version: ${{ matrix.dotnet-version }}.x
+        dotnet-version: ${{ matrix.version }}.x
         cache: true
         cache-dependency-path: |
           samples/**/packages.lock.json
@@ -37,114 +178,22 @@ jobs:
     - name: .NET Info
       run: dotnet --info
     - name: Add DNS-records
-      run: ./.github/steps/ubuntu.add-dns-records.sh  
+      run: ./.github/steps/${{ matrix.os }}.add-dns-records.sh  
     - name: Install certificate
-      run: ./.github/steps/ubuntu.install-certificate.sh
+      run: ./.github/steps/${{ matrix.os }}.install-certificate.sh
     - name: Restore
       run: dotnet restore --locked-mode ./Ocelot.slnx
     - name: Build
-      run: dotnet build --no-restore ./Ocelot.slnx --framework net${{ matrix.dotnet-version }}.0
+      run: dotnet build --no-restore ./Ocelot.slnx --framework net${{ matrix.version }}.0          
     - name: Unit Tests
-      run: dotnet test --no-restore --no-build --verbosity normal --framework net${{ matrix.dotnet-version }}.0 --settings coverlet.runsettings ./test/Ocelot.UnitTests/Ocelot.UnitTests.csproj
+      run: dotnet test --no-restore --no-build --verbosity minimal --framework net${{ matrix.version }}.0 --settings coverlet.runsettings ./test/Ocelot.UnitTests/Ocelot.UnitTests.csproj
     - name: Acceptance Tests
-      run: dotnet test --no-restore --no-build --verbosity normal --framework net${{ matrix.dotnet-version }}.0 --settings coverlet.runsettings ./test/Ocelot.AcceptanceTests/Ocelot.AcceptanceTests.csproj
-
-  build-macos:
-    needs: build-linux
-    strategy:
-      matrix:
-        dotnet-version: [ 8, 9, 10 ]
-    runs-on: macos-latest
-    # continue-on-error: true
-    env:
-      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v6
-      - name: SH-scripts executable
-        run: |
-          chmod +x .github/steps/*.sh
-          ls -l .github/steps/*.sh
-      - name: Setup .NET ${{ matrix.dotnet-version }}
-        uses: actions/setup-dotnet@v5
-        with:
-          dotnet-version: ${{ matrix.dotnet-version }}.x
-          cache: true
-          cache-dependency-path: |
-            samples/**/packages.lock.json
-            src/**/packages.lock.json
-            test/**/packages.lock.json
-      - name: .NET Info
-        run: dotnet --info
-      - name: Add DNS-records
-        run: ./.github/steps/macos.add-dns-records.sh  
-      - name: Install certificate
-        run: ./.github/steps/macos.install-certificate.sh
-      - name: Restore
-        run: dotnet restore --locked-mode ./Ocelot.slnx
-      - name: Build
-        run: dotnet build --no-restore ./Ocelot.slnx --framework net${{ matrix.dotnet-version }}.0
-      - name: Unit Tests
-        run: dotnet test --no-restore --no-build --verbosity minimal --framework net${{ matrix.dotnet-version }}.0 --settings coverlet.runsettings ./test/Ocelot.UnitTests/Ocelot.UnitTests.csproj
-      - name: Acceptance Tests
-        run: dotnet test --no-restore --no-build --verbosity minimal --framework net${{ matrix.dotnet-version }}.0 --settings coverlet.runsettings ./test/Ocelot.AcceptanceTests/Ocelot.AcceptanceTests.csproj
-
-  build-windows:
-    needs: build-macos
-    strategy:
-      matrix:
-        dotnet-version: [ 8, 9, 10 ]
-    runs-on: windows-latest
-    # continue-on-error: true
-    env:
-      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v6
-      - name: Setup .NET ${{ matrix.dotnet-version }}
-        uses: actions/setup-dotnet@v5
-        with:
-          dotnet-version: ${{ matrix.dotnet-version }}.x
-          cache: true
-          cache-dependency-path: |
-            samples/**/packages.lock.json
-            src/**/packages.lock.json
-            test/**/packages.lock.json
-      - name: .NET Info
-        run: dotnet --info
-      - name: Add DNS-records
-        run: ./.github/steps/windows.add-dns-records.ps1  
-      - name: Install certificate
-        run: ./.github/steps/windows.install-certificate.ps1
-      - name: Restore
-        run: dotnet restore --locked-mode ./Ocelot.slnx
-      - name: Build
-        run: dotnet build --no-restore ./Ocelot.slnx --framework net${{ matrix.dotnet-version }}.0
-      - name: Unit Tests
-        run: dotnet test --no-restore --no-build --verbosity minimal --framework net${{ matrix.dotnet-version }}.0 --settings coverlet.runsettings ./test/Ocelot.UnitTests/Ocelot.UnitTests.csproj
-      - name: Acceptance Tests
-        run: dotnet test --no-restore --no-build --verbosity minimal --framework net${{ matrix.dotnet-version }}.0 --settings coverlet.runsettings ./test/Ocelot.AcceptanceTests/Ocelot.AcceptanceTests.csproj
-
-  build-success:
-    needs: [build-linux, build-macos, build-windows]
-    runs-on: ubuntu-latest
-    if: ${{ always() }} # run even Linux / MacOS / Windows build fails
-    steps:
-      - name: Decide success
-        run: |
-          linux_result="${{ needs.build-linux.result }}"
-          macos_result="${{ needs.build-macos.result }}"
-          windows_result="${{ needs.build-windows.result }}"
-          if [[ $linux_result == "success" || $macos_result == "success" || $windows_result == "success" ]]; then
-            echo "At least one succeeded"
-          else
-            echo "All failed"
-            exit 1
-          fi
+      run: dotnet test --no-restore --no-build --verbosity minimal --framework net${{ matrix.version }}.0 --settings coverlet.runsettings ./test/Ocelot.AcceptanceTests/Ocelot.AcceptanceTests.csproj
 
   build-cake:
-    needs: build-windows
+    # needs: build-windows
     # needs: [build-linux, build-macos, build-windows]
+    needs: build
     runs-on: ubuntu-latest
     # environment: Pull-Request
     env:
@@ -160,10 +209,10 @@ jobs:
           chmod +x .github/steps/*.sh
           ls -l .github/steps/*.sh
       - name: Check .NET 10
-        id: check-dotnet10
+        id: checkdotnet
         run: ./.github/steps/check-dotnet.sh 10
       - name: Setup .NET 10
-        # if: env.DOTNET10_installed == 'false'
+        # if: steps.checkdotnet.outputs.checkdotnet_installed == 'false'
         uses: actions/setup-dotnet@v5
         with:
           dotnet-version: 10.x
